// <auto-generated />
using System;
using Atolla.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace Atolla.Domain.Migrations
{
    [DbContext(typeof(AtollaObjectContext))]
    [Migration("20201212174324_configuration")]
    partial class configuration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Atolla.Domain.General.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfigurationKey")
                        .HasColumnName("CONFIGURATION_KEY")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ConfigurationValue")
                        .HasColumnName("CONFIGURATION_VALUE")
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("CREATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Environment")
                        .HasColumnName("ENVIRONMENT")
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<short>("RowStatus")
                        .HasColumnName("ROW_STATUS")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnName("UPDATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnName("UPDATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("CONFIGURATION");
                });

            modelBuilder.Entity("Atolla.Domain.General.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("CREATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("GroupCode")
                        .HasColumnName("GROUP_CODE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("GroupName")
                        .HasColumnName("GROUP_NAME")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<short>("RowStatus")
                        .HasColumnName("ROW_STATUS")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnName("UPDATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnName("UPDATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("GROUP");
                });

            modelBuilder.Entity("Atolla.Domain.General.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("CREATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("GroupCode")
                        .HasColumnName("GROUP_CODE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("GroupId")
                        .HasColumnName("GROUP_ID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ParameterCode")
                        .HasColumnName("PARAMETER_CODE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ParameterDescription")
                        .HasColumnName("PARAMETER_DESCRIPTION")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ParameterName")
                        .HasColumnName("PARAMETER_NAME")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<short>("RowStatus")
                        .HasColumnName("ROW_STATUS")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnName("UPDATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnName("UPDATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("PARAMETER");
                });
#pragma warning restore 612, 618
        }
    }
}
