// <auto-generated />
using System;
using Atolla.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace Atolla.Domain.Migrations
{
    [DbContext(typeof(AtollaObjectContext))]
    partial class AtollaObjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Atolla.Domain.General.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfigurationKey")
                        .IsRequired()
                        .HasColumnName("CONFIGURATION_KEY")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ConfigurationValue")
                        .IsRequired()
                        .HasColumnName("CONFIGURATION_VALUE")
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("CREATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Environment")
                        .HasColumnName("ENVIRONMENT")
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<short>("RowStatus")
                        .HasColumnName("ROW_STATUS")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnName("UPDATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnName("UPDATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("CONFIGURATION");
                });

            modelBuilder.Entity("Atolla.Domain.General.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("CREATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("GroupCode")
                        .HasColumnName("GROUP_CODE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("GroupName")
                        .HasColumnName("GROUP_NAME")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<short>("RowStatus")
                        .HasColumnName("ROW_STATUS")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnName("UPDATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnName("UPDATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("GROUP");
                });

            modelBuilder.Entity("Atolla.Domain.General.Localization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("NUMBER(19)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("CREATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnName("LANGUAGE_CODE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<short>("RowStatus")
                        .HasColumnName("ROW_STATUS")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("StringKey")
                        .IsRequired()
                        .HasColumnName("STRING_KEY")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StringValue")
                        .IsRequired()
                        .HasColumnName("STRING_VALUE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnName("UPDATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnName("UPDATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("LOCALIZATION");
                });

            modelBuilder.Entity("Atolla.Domain.General.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("NUMBER(19)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("CREATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("MethodName")
                        .HasColumnName("METHOD_NAME")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<int>("ProcessTime")
                        .HasColumnName("PROCESS_TIME")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("RequestData")
                        .HasColumnName("REQUEST_DATA")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnName("REQUEST_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ResponceData")
                        .HasColumnName("RESPONSE_DATA")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ResponseDate")
                        .HasColumnName("RESPONSE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<short>("RowStatus")
                        .HasColumnName("ROW_STATUS")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("ServiceName")
                        .HasColumnName("SERVICE_NAME")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UpdatedBy")
                        .HasColumnName("UPDATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnName("UPDATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("LOG");
                });

            modelBuilder.Entity("Atolla.Domain.General.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("CREATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("GroupCode")
                        .HasColumnName("GROUP_CODE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("GroupId")
                        .HasColumnName("GROUP_ID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ParameterCode")
                        .HasColumnName("PARAMETER_CODE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ParameterDescription")
                        .HasColumnName("PARAMETER_DESCRIPTION")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ParameterName")
                        .HasColumnName("PARAMETER_NAME")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<short>("RowStatus")
                        .HasColumnName("ROW_STATUS")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnName("UPDATE_BY")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnName("UPDATE_DATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("PARAMETER");
                });
#pragma warning restore 612, 618
        }
    }
}
